server:
    port: 9000
spring:
    application:
        name: client-service
    security:
        oauth2:
            client:
                registration:
                    client-service:
                        provider: keycloak
                        client-id: client-service
                        client-secret: QVKK6GzlctkxQ7AnecRnDpNiRUBNl4OK
                        authorization-grant-type: client_credentials
                provider:
                    keycloak:
                        token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
